name: GINKGO-14

on: # [push]
  workflow_dispatch:
  watch:
    types: [started]

env:
  TG_CHAT_ID:  ${{ secrets.CHAT_ID }}
  TG_TOKEN: ${{ secrets.BOT_API }}
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20211029
    steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Initialize environment
          run: |
           chmod +x initialize
           bash initialize
        - name: Starting build
          run: |
           git clone https://github.com/SoniC-XIV/xiaomi_kernel_ginkgo -b Project SONIC
           cp ginkgo-14.sh SONIC && cd SONIC
           chmod +x ginkgo-14.sh && bash ginkgo-14.sh
