name: MIUI-A13

on: # [push]
  workflow_dispatch:
  watch:
    types: [started]

env:
  TG_CHAT_ID:  ${{ secrets.CHAT_ID }}
  TG_TOKEN: ${{ secrets.BOT_API }}
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20211029
    steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Initialize environment
          run: |
           chmod +x initialize
           bash initialize
        - name: Starting build
          run: |
           git clone --depth=1 https://github.com/SoniC-XIV/kernel_xiaomi_sm6150 -b 13 SONIC
           cp miui-a13.sh SONIC && cd SONIC
           chmod +x miui-a13.sh && bash miui-a13.sh
